version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: nestjs-auth
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongo

volumes:
  mongo-data:
